second
wso2-extensions/identity-outbound-auth-naver pull request #1
Opened 2020-07-06 17:45 UTC by krishnilak

## Purpose
> Describe the problems, issues, or needs driving this feature/fix and include links to related issues in the following format: Resolves issue1, issue2, etc.

## Goals
> Describe the solutions that this feature/fix will introduce to resolve the problems described above

## Approach
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to a Markdown file or Google doc if the feature write-up is too long to paste here.

## User stories
> Summary of user stories addressed by this change>

## Release note
> Brief description of the new feature or bug fix as it will appear in the release notes

## Documentation
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact

## Training
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if applicable

## Certification
> Type “Sent” when you have provided new/updated certification questions, plus four answers for each question (correct answer highlighted in bold), based on this change. Certification questions/answers should be sent to certification@wso2.com and NOT pasted in this PR. If there is no impact on certification exams, type “N/A” and explain why.

## Marketing
> Link to drafts of marketing content that will describe and promote this feature, including product page changes, technical articles, blog posts, videos, etc., if applicable

## Automation tests
 - Unit tests 
   > Code coverage information
 - Integration tests
   > Details about the test cases and coverage

## Security checks
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes/no
 - Ran FindSecurityBugs plugin and verified report? yes/no
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes/no

## Samples
> Provide high-level details about the samples related to this feature

## Related PRs
> List any other related PRs

## Migrations (if applicable)
> Describe migration steps and platforms on which migration has been tested

## Test environment
> List all JDK versions, operating systems, databases, and browser/versions on which this feature/fix was tested
 
## Learning
> Describe the research phase and any blog posts, patterns, libraries, or add-ons you used to solve the problem.

2020-07-06 17:45 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/wso2-extensions/identity-outbound-auth-naver?pullRequest=1) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/wso2-extensions/identity-outbound-auth-naver?pullRequest=1) before we can accept your contribution.<br/><hr/>**krishnia@wso2.com** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/wso2-extensions/identity-outbound-auth-naver?pullRequest=1) it.</sub>

2020-07-07 03:19 UTC, GDRDABARERA commented on .classpath
> +		<attributes>
Shall we remove this .xxxx files. Do we need these to do a maven clean repo build without an IDE

2020-07-07 03:20 UTC, GDRDABARERA commented on .settings/org.eclipse.jdt.core.prefs
> +org.eclipse.jdt.core.compiler.codegen.targetPlatform=1.7
Remove these files

2020-07-07 03:20 UTC, GDRDABARERA commented on pom.xml
> +  Copyright 2015 WSO2 Inc. (http://wso2.org)
Add the latest 2020 license header

2020-07-07 03:21 UTC, GDRDABARERA commented on pom.xml
> +	<version>0.0.1-SNAPSHOT</version>
Lets make this 1.0.0-SNAPHOT as we release 1.0.0 version first

2020-07-07 03:25 UTC, GDRDABARERA requested changes

2020-07-07 03:25 UTC, GDRDABARERA commented on pom.xml
> +			<version>3.5.100.v20160504-1419</version>
We do not use org.eclipse.osgi.services , instead  use <groupId>org.apache.felix</groupId> <artifactId>maven-bundle-plugin</artifactId>

Use the same format we used in other connectors https://github.com/wso2-extensions/identity-outbound-auth-facebook/blob/master/components/org.wso2.carbon.identity.application.authenticator.facebook/pom.xml#L20

2020-07-07 03:25 UTC, GDRDABARERA commented on pom.xml
> +				<version>3.2.0</version>
Lets move versions to a <properties> and refer them here

2020-07-07 03:54 UTC, GDRDABARERA requested changes

2020-07-07 03:54 UTC, GDRDABARERA commented on target/maven-shared-archive-resources/META-INF/DEPENDENCIES
> +// ------------------------------------------------------------------
Remove target and all class files.

2020-07-07 03:54 UTC, GDRDABARERA commented on src/main/java/org/wso2/carbon/identity/application/authenticator/social/naver/internal/NaverAuthenticatorServiceComponent.java
> +            logger.info("----Naver Authenticator bundle is activated----");
Lets add this in a debug log as
 if (log.isDebugEnabled()) {
logger.debug("Naver Authenticator bundle is activated" );
 }

2020-07-07 03:54 UTC, GDRDABARERA commented on src/main/java/org/wso2/carbon/identity/application/authenticator/social/naver/internal/NaverAuthenticatorServiceComponent.java
> +        logger.info("----Naver Authenticator bundle is deactivated----");
Let's add this as a debugger log too.

2020-07-07 03:54 UTC, GDRDABARERA commented on src/main/java/org/wso2/carbon/identity/application/authenticator/social/naver/NaverCustomAuthenticator.java
> + * Copyright 2015 WSO2 Inc. (http://wso2.org)
Change license header to latest

2020-07-07 03:54 UTC, GDRDABARERA commented on src/main/java/org/wso2/carbon/identity/application/authenticator/social/naver/internal/NaverAuthenticatorServiceComponent.java
> + * Copyright 2015 WSO2 Inc. (http://wso2.org)
Change license header to latest 2020

2020-07-07 03:54 UTC, GDRDABARERA commented on src/main/java/org/wso2/carbon/identity/application/authenticator/social/naver/internal/NaverAuthenticatorServiceComponent.java
> +immediate = true)
Check formating, use 120 line length

2020-07-07 03:54 UTC, GDRDABARERA commented on src/main/java/org/wso2/carbon/identity/application/authenticator/social/naver/internal/NaverAuthenticatorServiceComponent.java
> +	@Activate
Formating issue, use wso2 checkstyles

2020-07-07 03:54 UTC, GDRDABARERA commented on src/main/java/org/wso2/carbon/identity/application/authenticator/social/naver/NaverCustomAuthenticatorConstants.java
> +	public static final String CLIENT_ID = "ClientId";
formatting issue

2020-07-07 03:54 UTC, GDRDABARERA commented on src/main/java/org/wso2/carbon/identity/application/authenticator/social/naver/NaverCustomAuthenticatorConstants.java
> + * Copyright 2015 WSO2 Inc. (http://wso2.org)
License header to 2020 one

2020-07-07 03:54 UTC, GDRDABARERA commented on src/main/java/org/wso2/carbon/identity/application/authenticator/social/naver/NaverCustomAuthenticator.java
> +		return "https://nid.naver.com/oauth2.0/authorize";
Shall we add these URLs to constants.

2020-07-07 03:54 UTC, GDRDABARERA commented on src/main/java/org/wso2/carbon/identity/application/authenticator/social/naver/NaverCustomAuthenticator.java
> +		return "NAVER";
Add these strings to static final strings

2020-07-07 03:54 UTC, GDRDABARERA commented on src/main/java/org/wso2/carbon/identity/application/authenticator/social/naver/NaverCustomAuthenticator.java
> +	public String getContextIdentifier(HttpServletRequest request) {
Keep one line space after method signature in all places

2020-07-07 03:54 UTC, GDRDABARERA commented on src/main/java/org/wso2/carbon/identity/application/authenticator/social/naver/NaverCustomAuthenticator.java
> +	protected void initiateAuthenticationRequest(HttpServletRequest request, HttpServletResponse response,
Keep one line space after method signature in all places

2020-07-07 03:54 UTC, GDRDABARERA commented on src/main/java/org/wso2/carbon/identity/application/authenticator/social/naver/NaverCustomAuthenticator.java
> +			logger.info("authzRequest");
Use this in debugs logs, remove unwanted info logs

2020-07-07 03:54 UTC, GDRDABARERA commented on src/main/java/org/wso2/carbon/identity/application/authenticator/social/naver/NaverCustomAuthenticator.java
> +		logger.info("processAuthenticationResponse");
Remove unwanted info logs and trace logs

2020-07-07 03:54 UTC, GDRDABARERA commented on src/main/java/org/wso2/carbon/identity/application/authenticator/social/naver/NaverCustomAuthenticator.java
> +				logger.debug("code >>>>>>> " + code);
put this inside if(isDebugEnabled(){)

2020-07-07 03:54 UTC, GDRDABARERA commented on src/main/java/org/wso2/carbon/identity/application/authenticator/social/naver/NaverCustomAuthenticator.java
> +				logger.debug("token >>>>>>> " + token);
Shall we put this in a audit log, lets make sure whether its safe to log this token and code here

2020-07-07 03:54 UTC, GDRDABARERA commented on src/main/java/org/wso2/carbon/identity/application/authenticator/social/naver/NaverCustomAuthenticator.java
> +				logger.error("State token validation failed");
Shall we throw an exception here?

2020-07-07 03:54 UTC, GDRDABARERA commented on src/main/java/org/wso2/carbon/identity/application/authenticator/social/naver/NaverCustomAuthenticator.java
> +
remove unwanted line space

2020-07-07 03:54 UTC, GDRDABARERA commented on src/main/java/org/wso2/carbon/identity/application/authenticator/social/naver/NaverCustomAuthenticator.java
> +		StringBuilder b = new StringBuilder();
use proper variable names

2020-07-07 03:54 UTC, GDRDABARERA commented on src/main/java/org/wso2/carbon/identity/application/authenticator/social/naver/NaverCustomAuthenticator.java
> +		logger.info("sendRequest");
Remove these info logs, they are not wanted, it slow downs the flow

2020-07-07 06:31 UTC, GDRDABARERA commented on pom.xml
> +		<version>1</version>
Use 1.2 version

2020-07-07 06:33 UTC, GDRDABARERA requested changes

2020-07-07 06:33 UTC, GDRDABARERA commented on src/main/java/org/wso2/carbon/identity/application/authenticator/social/naver/internal/NaverAuthenticatorServiceComponent.java
> +            logger.debug("----Naver Authenticator bundle is activated----");
Formatting issue

2020-07-07 06:33 UTC, GDRDABARERA commented on src/main/java/org/wso2/carbon/identity/application/authenticator/social/naver/internal/NaverAuthenticatorServiceComponent.java
> +        logger.debug("----Naver Authenticator bundle is deactivated----");
Formatting issue. use wso2 checkstyles

2020-07-07 06:33 UTC, GDRDABARERA commented on src/main/java/org/wso2/carbon/identity/application/authenticator/social/naver/internal/NaverAuthenticatorServiceComponent.java
> +	protected void deactivate(ComponentContext ctxt) {
Keep oneline space after method signature

2020-07-07 06:33 UTC, GDRDABARERA commented on src/main/java/org/wso2/carbon/identity/application/authenticator/social/naver/NaverCustomAuthenticator.java
> +			if (userInfoJson.has("email"))
Lets add constants for all these user attributes

2020-07-08 05:31 UTC, GDRDABARERA requested changes

2020-07-08 05:31 UTC, GDRDABARERA commented on bin/pom.xml
> +			<version>3.5.100.v20160504-1419</version>
Put versions as properties

2020-07-08 05:31 UTC, GDRDABARERA commented on bin/pom.xml
> +		<version>1</version>
Use 1.2 version

2020-07-08 05:31 UTC, GDRDABARERA commented on src/main/java/org/wso2/carbon/identity/application/authenticator/social/naver/NaverCustomAuthenticator.java
> +	protected String getAuthorizationCode(HttpServletRequest request) throws ApplicationAuthenticatorException {
One line space

2020-07-08 05:31 UTC, GDRDABARERA commented on src/main/java/org/wso2/carbon/identity/application/authenticator/social/naver/NaverCustomAuthenticator.java
> +	protected String sendRequest(String url) throws IOException {
One lien space

2020-07-08 05:31 UTC, GDRDABARERA commented on src/main/java/org/wso2/carbon/identity/application/authenticator/social/naver/NaverCustomAuthenticator.java
> +public class NaverCustomAuthenticator extends AbstractApplicationAuthenticator
Add class level comment

2020-07-08 05:31 UTC, GDRDABARERA commented on src/main/java/org/wso2/carbon/identity/application/authenticator/social/naver/NaverCustomAuthenticator.java
> +	protected String getToken(String tokenEndPoint, String clientId, String clientSecret, String code)
Add method level comment

2020-07-08 05:31 UTC, GDRDABARERA commented on src/main/java/org/wso2/carbon/identity/application/authenticator/social/naver/NaverCustomAuthenticator.java
> +	protected OAuthClientRequest buidTokenRequest(String tokenEndPoint, String clientId, String clientSecret,
add method level comment

2020-07-08 05:31 UTC, GDRDABARERA commented on src/main/java/org/wso2/carbon/identity/application/authenticator/social/naver/NaverCustomAuthenticator.java
> +			String state, String code) throws ApplicationAuthenticatorException {
Line space

2020-07-08 05:31 UTC, GDRDABARERA commented on src/main/java/org/wso2/carbon/identity/application/authenticator/social/naver/NaverCustomAuthenticator.java
> +	public boolean canHandle(HttpServletRequest request) {
line space

2020-07-08 05:31 UTC, GDRDABARERA commented on src/main/java/org/wso2/carbon/identity/application/authenticator/social/naver/NaverCustomAuthenticator.java
> +	protected String getUserInfo(String apiUrl, Map<String, String> requestHeaders) {
line space

2020-07-08 05:31 UTC, GDRDABARERA commented on src/main/java/org/wso2/carbon/identity/application/authenticator/social/naver/NaverCustomAuthenticator.java
> +	protected HttpURLConnection connect(String apiUrl) {
line space

2020-07-08 05:31 UTC, GDRDABARERA commented on src/main/java/org/wso2/carbon/identity/application/authenticator/social/naver/NaverCustomAuthenticator.java
> +	protected String readBody(InputStream body) {
line space

2020-07-08 05:31 UTC, GDRDABARERA commented on src/main/java/org/wso2/carbon/identity/application/authenticator/social/naver/NaverCustomAuthenticator.java
> +	protected boolean isOauth2CodeParamExists(HttpServletRequest request) {
line space

2020-07-08 05:56 UTC, GDRDABARERA requested changes

2020-07-08 05:56 UTC, GDRDABARERA commented on src/test/resources/testing.xml
> +</suite>
new line

2020-07-08 05:56 UTC, GDRDABARERA commented on src/main/java/org/wso2/carbon/identity/application/authenticator/social/naver/internal/NaverAuthenticatorServiceComponent.java
> +	protected void activate(ComponentContext ctxt) {
new line space

2020-07-08 05:56 UTC, GDRDABARERA commented on src/main/java/org/wso2/carbon/identity/application/authenticator/social/naver/NaverCustomAuthenticatorConstants.java
> +	public static final String NAVER_PARAM_STATE = "state";
Formatting issue

2020-07-08 05:56 UTC, GDRDABARERA commented on src/main/java/org/wso2/carbon/identity/application/authenticator/social/naver/internal/NaverAuthenticatorServiceComponent.java
> +			logger.fatal("----Error while activating Naver authenticator----", e);
log.error

2020-07-08 05:56 UTC, GDRDABARERA commented on src/test/java/org/wso2/carbon/identity/application/authenticator/social/naver/NaverAuthenticatorTests.java
> +    public void setUp() throws Exception {
Line space

2020-07-08 05:56 UTC, GDRDABARERA commented on src/main/java/org/wso2/carbon/identity/application/authenticator/social/naver/NaverCustomAuthenticatorConstants.java
> +
remove unnecessory lines

2020-07-08 05:56 UTC, GDRDABARERA commented on src/main/java/org/wso2/carbon/identity/application/authenticator/social/naver/NaverCustomAuthenticator.java
> +
remove line

2020-07-08 05:56 UTC, GDRDABARERA commented on src/main/java/org/wso2/carbon/identity/application/authenticator/social/naver/NaverCustomAuthenticator.java
> +	protected String getLoginType(HttpServletRequest request) {
new line

2020-07-08 05:56 UTC, GDRDABARERA commented on src/main/java/org/wso2/carbon/identity/application/authenticator/social/naver/NaverCustomAuthenticator.java
> +	protected boolean isOauthStateParamExists(HttpServletRequest request) {
new line

2020-07-08 05:56 UTC, GDRDABARERA commented on src/main/java/org/wso2/carbon/identity/application/authenticator/social/naver/NaverCustomAuthenticator.java
> +	protected String generateState() {
new line

2020-07-08 05:56 UTC, GDRDABARERA commented on src/main/java/org/wso2/carbon/identity/application/authenticator/social/naver/NaverCustomAuthenticator.java
> +	public String getFriendlyName() {
new line

2020-07-08 10:30 UTC, krishnilak commented on bin/pom.xml
> +			<version>3.5.100.v20160504-1419</version>
Removed bin folder

2020-07-08 10:30 UTC, krishnilak commented on bin/pom.xml
> +		<version>1</version>
removed bin folder

2020-07-08 10:31 UTC, krishnilak commented on src/main/java/org/wso2/carbon/identity/application/authenticator/social/naver/NaverCustomAuthenticator.java
> +	protected String readBody(InputStream body) {
Hope these are fixed with added style formatter

2020-07-10 08:42 UTC, closed without merging